#!/bin/bash

source /projects/tomancak_lightsheet/Christopher/pipeline/master

mkdir -p $jobs_resaving

for i in $timepoint

do
	for a in $angle_resaving
	do
		job="$jobs_resaving_ometiff/resave-$i-$a.job"
		echo $job
		echo "$XVFB_RUN -a $Fiji -Ddir=$dir -Dtimepoint=$i -Dangle=$a \
			-Dpad=$pad_resave -- --no-splash $resaving_ometiff" >> "$job"
		chmod a+x "$job"
	done
done
