#!/bin/bash
 
####============================= Processing Parameters ==============================

#This is the master file for 2014-04-21_Stock14_Stock19
 
####------------------------------ General Parameters --------------------------------
###Data directory
#dir="/projects/pilot_spim/Christopher/Test_scripts/single-channel/"
dir="/projects/pilot_spim/Christopher/2014-04-21_Stock14_Stock19/"
 
###Dataset core parameters
timepoint="`seq 1 19`"
#timepoint="1"
angles="1,2,3,4,5"
num_angles="5"
 
## pattern of spim data: padded zeros use tt as place holder
## change pattern for single-channel: (e.g. spim_TL{tt}_Angle{a}.tif)
## for multi-channel processing: (e.g. spim_TL{tt}_Angle{a}_Channel{c}.tif)
#pattern_of_spim="spim_TL{t}_Angle{a}.tif"
pattern_of_spim="spim_TL{tt}_Angle{a}_Channel{c}.tif"
 
#Timelapse registration
referencetp="9"
 
##Manual calibration
xy_resolution="1"
z_scaling="3.2258064"
 
###---------- Renaming .czi files ----------
first_index="0"
last_index="94"
first_timepoint="1"
angles_renaming=(1 2 3 4 5)
 
##For padded zero 2 = 01; 3 = 001
pad_rename_czi="2"
 
##Change directory and patternls
source_pattern=/2014-04-21_Stock14_Stock19_2\(\{index\}\).czi
target_pattern=/spim_TL\{timepoint\}_Angle\{angle\}.czi
 
###---------- Resaving .czi or ome.tiff as .tif ----------
##use ometiff_resave for ome.tiff and czi_resave for .czi
angle_resaving="1 2 3 4 5"
 
##For padded zero 2 = 01; 3 = 001
pad_resave="2"
 
###---------- Split Channels (Only for multi-channel data) ----------
##Outputs channls as spim_TL{tt}_Angle{a}_Channel0,spim_TL{tt}_Angle{a}_Channel1 ...
angles_split="1 2 3 4 5"

##Target directory
target_split="/"
 
###---------- Multi-view registration (Difference of mean or Difference of Gaussian) ----------
##Specify the Pattern for Detection of the beads single channel: spim_TL{t}_Angle{a}.tif
##multi-channel: spim_TL{t}_Angle{a}_Channel1.tif were 1 is the Channel that contains the beads
#channel_pattern_beads="spim_TL{t}_Angle{a}.tif"
channel_pattern_beads="spim_TL{tt}_Angle{a}_Channel1.tif"
 
##Difference of mean (Comment out Difference of Gaussian parts in registration.bsh script)
type_of_detection="\"Difference-of-Mean (Integral image based)\""
radius1="2"
radius2="3"
threshold="0.010"

#Difference of Gaussian (Comment out Differnce of Mean parts in registration.bsh script)
#type_of_detection="\"Difference-of-Gaussian\""
#initial_sigma="1.8000"
#threshold_gaussian="0.0080"
 
###---------- Timelapse registration ----------
timelapse_timepoint="1-19"
 
###---------- Dublicate Registration files (Only for multi-channel data) ----------
#Channel that contain the beads
channel_source="1"
channel_target="0"
 
###---------- Multi-view content based fusion ----------
##Change between Single-Channel or Mulit-channel fusion
##If single channel then comment out 2nd fusion command in fusion.bsh script
#select_channel="Single-channel"
select_channel="Multi-channel"
 
##Use timelapse registration or Individual registration
##For timelapse registration specify reference timepoint:
registration_fusion="\"Time-point registration (reference=9) of channel 0\""
registration_fusion1="\"Time-point registration (reference=9) of channel 1\""
##Individual registration:
#"\"Individual registration of channel 0\""

##Downsampling
downsample_output="1"
 
##Cropping parameters of full resolution
x="4"
y="310"
z="280"
w="1848"
h="698"
d="710"
 
###---------- External transformation for multi-view deconvolution ----------
##Only single channel, use external transformation for each individual channel
##For downsampling 2x use 0.5
#Caution: Before applying the exteranl transformation make a copy of the registration files
pattern_extrans="spim_TL{t}_Angle{a}.tif"
#pattern_extrans="spim_TL{tt}_Angle{a}_Channel1.tif"

##Timepoints
external_transformation_timepoint="1-200"

##Downsampling
m00="0.5"
m11="0.5"
m22="0.5"
 
###---------- Multi-view deconvolution ----------
##Only for single channel, use deconvolution for each individual channel
pattern_deconvo="spim_TL{t}_Angle{a}.tif"
#pattern_deconvo="spim_TL{tt}_Angle{a}_Channel1.tif"

##Number of iterations
iter="10"

##PSF parameters 
psf_estimation="\"Extract from beads\""
#psf_estimation= 

##Cropping parameters: if downsampled divid fusion cropping parameters by this factor
decox="19"
decoy="181"
decoz="143"
decow="928"
decoh="405"
decod="447"
 
###---------- Rendering ----------
##Two different sets of scripts, one for single channel and one for multi-channel; choose:
##Working directory
jobs_rendering="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/3d_rendering_cpu"
 
##Working script
rendering="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/3d_rendering_cpu/single-render-mov.bsh"
#rendering="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/3d_rendering_cpu/multi-render-mov.bsh" 

##source
source_rendering="/output"
 
##target directory
target_rendering="/rendering"

#nframes for rotation 
nframes="6"

##Min Max single channel
minimum_rendering="0.5"
maximum_rendering="0.005"

##Min Max multi channel
#min_ch0=0.9
#max_ch0=0.01

#min_ch1=0.9
#max_ch1=0.01
 
##For multi-channel rendering:
#zSlices="369"
 
##Orientation or rotation

#rotation_lateral: 3d-affine: (0.9736341, -0.090486586, 0.2094066, 0.0, 
#				-0.18908852, -0.8336387, 0.51894456, 0.0, 
#				0.12761092, -0.5448576, -0.8287677, 0.0)
#still needs to be put into the script directly
#under construction
 
###---------- hdf5 export ----------
##Target directory
target_hdf5="/hdf5/"

##Number of jobs
num_export_job="`seq 0 11`"

#Path directory
#path="\"/projects/pilot_spim/Christopher/2014-03-23_Stock5_Test\""
path="\"/projects/pilot_spim/Christopher/2014-04-21_Stock14_Stock19/\""

#Xml filename
exportXmlFilename="\"/hdf5/2014-04-21_Stock14_Stock19.xml\"" 

##Spim pattern 
##For single channel:spim_TL{tt}_Angle{a}.tif
##For 2 channel: spim_TL{tt}_Angle{a}_Channel{c}.tif
#inputFilePattern="\"spim_TL{t}_Angle{a}.tif\""
inputFilePattern="\"spim_TL{tt}_Angle{a}_Channel{c}.tif\""

##Channels: change for 2 channel data
#channels_export="\"0\""
channels_export="\"0,1\""

angles_export="\"1,2,3,4,5\""
timepoint_export="\"1-19\""
referencetp_export="\"9\""

filepath="\"/output/\""
filepattern="\"%1\\\$d/img_tl%1\\\$d_ch%2\\\$d_z%3\\\$03d.tif\""

export_numSlices="710"
sliceValueMin="0"
sliceValueMax="60000"

cropOffsetX="4"
cropOffsetY="310"
cropOffsetZ="280" 
scale="1"

####============== Directories for scripts and advanced settings for processing ==============
 
####--------------------------------- Fiji settings ---------------------------------
 
XVFB_RUN="/sw/bin/xvfb-run"
Fiji="/sw/users/tomancak/packages/Fiji.app/ImageJ-linux64"
 
####--------------------------------- Pre-processing ---------------------------------
### Resaving .czi into .tif files
##Working directory
jobs_resaving="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/czi_resave/"
 
##Working script
resaving="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/czi_resave/resaving.bsh"
 
###Resaving ome.tiff into .tif files
##Working directory
jobs_resaving_ometiff="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/ometiff_resave/"
 
##Working script
resaving_ometiff="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/ometiff_resave/resaving-ometiff.bsh"
 
###Split channels
##Working directory
jobs_split="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/split_channels/"
 
##Working script
split="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/split_channels/split.bsh"
 
 
####--------------------------------- Multi-view Registration ---------------------------------
##Working directory
jobs_registration="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/registration/"
 
##Working script
registration="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/registration/registration.bsh"
 
##registration parameters
type_of_registration="Single-channel"
bead_brightness="\"Advanced ...\""
subpixel_localization="\"3-dimensional quadratic fit (all detections)\""
transformation_model="Affine"
imglib_container="\"Array container (images smaller ~2048x2048x450 px)\""
 
####--------------------------------- Timelapse registration ---------------------------------
##Working directory
jobs_timelapse="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/timelapse_registration/"
 
##Working script
timelapse_registration="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/timelapse_registration/time-lapse.bsh"
 
####--------------------------------- Multi-view fusion ----------------------------------------
##Working directory
jobs_fusion="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/fusion/"
 
##Working script
fusion="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/fusion/fusion.bsh"
 
##Fusion parameters
fusion_method="\"Fuse into a single image\""
process_views_in_paralell="All"
blending="blending"
weights="\"content_based_weights_(fast,\""
fused_image_output="\"Save 2d-slices, one directory per time-point\""
 
####--------------------------------- External transformation ---------------------------------
##Working directory
jobs_external_transformation="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/external_transformation/"
 
##Working script
external_transformation="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/external_transformation/external_transformation.bsh"
 
####--------------------------------- Multi-view deconvolution ---------------------------------
##Working directory
jobs_deconvolution="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/deconvolution/"
 
##Working script
deconvolution="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/deconvolution/deconvolution.bsh"
 
##Deconvolution parameters
type_of_iteration="\"Efficient Bayesian - Optimization I (fast, precise)\""
osem_acceleration="\"1 (balanced)\""
use_tikhonov_regularization="use_tikhonov_regularization"
Tikhonov_parameter="0.0006"
compute="\"in 512x512x512 blocks\""
compute_on="\"CPU (Java)\""
 
psf_display="\"Do not show PSF's\""
load_input_images_sequentially="load_input_images_sequentially"
fused_image_output="\"Save 2d-slices, one directory per time-point\""
 
####--------------------------------- Rendering ---------------------------------
##Fiji for rendering
Fiji_rendering="/sw/users/tomancak/packages/Fiji.app.render/ImageJ-linux64"

####--------------------------------- hdf5 export ---------------------------------

##Fiji_tobias
Fiji_export="/sw/users/pietzsch/packages/Fiji.app/ImageJ-linux64"

##Working directory
jobs_export="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/hdf5/"

##Working script
export="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0/hdf5/export.bsh"

##overrideImageZStretching does not work
#overrideImageZStretching="true" 

##Not implemented yet
#spimresolutions="{ { 1, 1, 1 }, { 2, 2, 1 }, { 4, 4, 2 }, { 8, 8, 4 } }"
#spimsubdivisions="{ { 32, 32, 4 }, { 16, 16, 8 }, { 8, 8, 8 }, { 8, 8, 8 } }"

#fusionresolutions = "{ { 1, 1, 1 }, { 2, 2, 2 }, { 4, 4, 4 }, { 8, 8, 8 } }"
#fusionsubdivisions = "{ { 16, 16, 16 }, { 16, 16, 16 }, { 8, 8, 8 }, { 8, 8, 8 } }"

#################################################################################
# Cluster processing master file                                                #
# Christopher Schmied                                                           #
# Beta 2.1 version                                                              #
#################################################################################

