#!/bin/bash
#===============================================================================
#
#	  FILE: master 
#
#  DESCRIPTION: source file for cluster processing scripts
#
#       AUTHOR: Christopher Schmied, schmied@mpi-cbg.de
#    INSTITUTE: Max Planck Institute for Molecular Cell Biology and Genetics
#         BUGS: ---
#        NOTES: ---
#      Version: 1.1
#      CREATED: 2014-04-02
#     REVISION: 2014-05-16
#===============================================================================
 
#------------------------------------------------------------------------------- 
#                           General Parameters 
#
# Dataset: Test scripts
#
# Select single or multi channel:
# 	single channel: pattern_of_spim="spim_TL{tt}_Angle{a}.tif" 
# 	multi channel: pattern_of_spim="spim_TL{tt}_Angle{a}_Channel{c}.tif"
#-------------------------------------------------------------------------------

dir="/projects/pilot_spim/Christopher/Test_scripts/multi-channel/" # Data 
                   					           # directory
job_directory="/projects/pilot_spim/Christopher/pipeline/jobs_master_beta_2.0"
timepoint="`seq 1 2`"                          # timepoints format: "`seq 1 3`" 
angles="1,2,3,4,5"                             # angles format: "1,2,3" or "1-3"
num_angles="5" 					      # number of angles
pattern_of_spim="spim_TL{tt}_Angle{a}_Channel{c}.tif" # pattern of spim
						      # for padded zeros use tt
select_channel="Multi-channel"          # "Single-channel" or "Multi-channel" 
Channel_beads="1"			# Channel that contains the beads						      
pad="2"						      # For padded zeros
referencetp="1"					      # reference timepoint 
xy_resolution="1"				      # Manual calibration xy
z_scaling="3.481975"   			      # Manual calibration z
 
#-------------------------------------------------------------------------------
#                           Preprocessing 
# 
# Use czi_resave for .czi files and ometiff files for .ometiff files
#
# split.bsh for multi-channel data):
# Outputs channls as: spim_TL{tt}_Angle{a}_Channel0
#                     spim_TL{tt}_Angle{a}_Channel1
# saves into dir
#-------------------------------------------------------------------------------

#--- Renaming czi files --------------------------------------------------------

first_index="0"                                       # First index of czi files
last_index="14"					      # Last index
first_timepoint="1"                                   # The first timepoint 
angles_renaming=(1 2 3 4 5)                           # Angles format: (1 2 3)
						      						      
source_pattern=/2014-02-14_Stock19_Stock17\(\{index\}\).czi
target_pattern=/spim_TL\{timepoint\}_Angle\{angle\}.czi
 
#--- Resaving and splitting  ---------------------------------------------------

angle_prep="1 2 3 4 5"  # angles format: "1 2 3"

#=== Function ==================================================================
# 	 NAME: channel switch
# DESCRIPTION: changes the pattern to multichannel and uses padding
# Parameter 1: pattern_of_spim
# Parameter 2: select_channel
# Parameter 3: Channel_beads
#===============================================================================

padding="$( cut -d '_' -f 2 <<<$pattern_of_spim )";

if [ "$select_channel" == "Multi-channel" ]; then

        c2="_Channel${Channel_beads}"

                else
                        c2=""
fi

pattern_switch="\"spim_"$padding"_Angle{a}${c2}.tif\""

#-------------------------------------------------------------------------------
# 			   Multi-view registration 
#
# Specify the method for Detection of beads: 
#     Difference of mean: Comment out Difference of Gaussian in registration.bsh 
#     Difference of Gaussian: Comment out Differnce of Mean in registration.bsh
#-------------------------------------------------------------------------------

type_of_detection="\"Difference-of-Mean (Integral image based)\"" # Difference
radius1="2"							  # of Mean 
radius2="3"
threshold="0.009"

# type_of_detection="\"Difference-of-Gaussian\""		  # Difference 	
# initial_sigma="1.8000"					  # of Gaussian
# threshold_gaussian="0.0080"
 
#-------------------------------------------------------------------------------
#			  Timelapse registration 
#-------------------------------------------------------------------------------

timelapse_timepoint="1-2"
 
#------------------------------------------------------------------------------- 
#		      Dublicate Registration files 
#
# Only for multi-channel data
#-------------------------------------------------------------------------------

channel_source="1" 			# Channel that contains the beads
channel_target="0"			
 
#------------------------------------------------------------------------------- 
#		    Multi-view content based fusion 
# 
#  single channel: comment out 2nd fusion command in fusion.bsh
#   multi channel: comment in registration_fusion1
#
# Select timelapse registration or individual registration:
#  timelapse: 
#  registration_fusion="\"Time-point registration (reference=${referencetp}) of channel 0\""
#  
#  Individual:
#  registration_fusion="\"Individual registration of channel 0\""
#
#-------------------------------------------------------------------------------
  
registration_fusion="\"Time-point registration (reference=${referencetp}) of channel 0\""	
registration_fusion1="\"Time-point registration (reference=${referencetp}) of channel 1\""

downsample_output="2"                   # Downsampling
x="0"		                        # Cropping parameters of full resolution
y="314"
z="320"
w="1858"
h="758"
d="740"
 
#------------------------------------------------------------------------------- 
#          External transformation for multi-view deconvolution
#
# Only single channel, use external transformation for each individual channel
# Cation! make a copy of the registration files befor external transformation
# 
#-------------------------------------------------------------------------------

external_transformation_timepoint="1-2" 	  # Timepoints
m00="0.5" 					  # Downsampling 
m11="0.5"                                         # For downsampling 2x use 0.5
m22="0.5"
 
#------------------------------------------------------------------------------- 
#			  Multi-view deconvolution 
#
# Only for single channel, use deconvolution for each individual channel
# For multichannel data specify correct pattern:
# single: pattern_deconvo="spim_TL{t}_Angle{a}.tif"
# multi: pattern_deconvo="spim_TL{tt}_Angle{a}_Channel1.tif"
#-------------------------------------------------------------------------------

pattern_deconvo="spim_TL{tt}_Angle{a}_Channel1.tif"   # Pattern

iter="1"				    # Number of iterations
psf_estimation="\"Extract from beads\""     # PSF parameters 
# psf_estimation=                           # Does not work yet!
decox="0" 				    # Cropping parameters: 
decoy="157"				       # if downsampled divide 
decoz="160"				       # fusion cropping parameters 
decow="929"				       # by this factor
decoh="379"
decod="370"
 
#------------------------------------------------------------------------------- 
#				    Rendering 
# 
# One working scripts for single channel and one for multi-channel: 
# 	single: single-render-mov.bsh
# 	multi: multi-render-mov.bsh
#
# Different settings for single or for multi channel
#-------------------------------------------------------------------------------

#--- General settings ----------------------------------------------------------

jobs_rendering=${job_directory}"/3d_rendering_cpu"  # directory
rendering=${jobs_rendering}"/multi-render-mov.bsh" # script single or 
						    # multi-channel
source_rendering="/fusion_output"                   # source
target_rendering="/fusion_rendering"                # target directory
nframes="6"                                  # nframes for rotation 

#--- Settings single channel ---------------------------------------------------

minimum_rendering="0.5"                      # Min single channel
maximum_rendering="0.005"                    # Max single channel

#--- Settings multi channel ----------------------------------------------------

min_ch0=0.9 				     # Min channel 0 multi channel
max_ch0=0.01				     # Max channel 0 multi channel
min_ch1=0.9			             # Min channel 1 multi channel
max_ch1=0.01                               # Max channel 1 multi channel
zSlices="369" 			     # For multi-channel rendering:
 
#--- Orientation or rotation ---------------------------------------------------
# rotation_lateral: 3d-affine: (0.9736341, -0.090486586, 0.2094066, 0.0, 
#				-0.18908852, -0.8336387, 0.51894456, 0.0, 
#				0.12761092, -0.5448576, -0.8287677, 0.0)
# still needs to be put into the script directly
# under construction
 
#------------------------------------------------------------------------------- 
#				hdf5 export 
#
# Single or multi channel:
#                  single: channels_export="\"0\""
#                   multi: channels_export="\"0,1\""
#-------------------------------------------------------------------------------

target_hdf5="/hdf5/"				             # Target directory
num_export_job="`seq 0 2`"			             # Number of jobs
exportXmlFilename="\"${target_hdf5}2013-11-14_His-YFP.xml\"" # xml file
								     # name
channels_export="\"0,1\""				     # Channels
timepoint_export="\"1-2\""				     # timepoints
filepath="\"/fusion_output/\""				# directory of fused data
filepattern="\"%1\\\$d/img_tl%1\\\$d_ch%2\\\$d_z%3\\\$03d.tif\"" # fused data	
								 # pattern
export_numSlices="369"
sliceValueMin="0"			# Minimal intensity histogram
sliceValueMax="60000"			# Maximal intensity histogram
cropOffsetX="0"				# x crop
cropOffsetY="314"			# y crop
cropOffsetZ="320" 			# z crop
scale="2"				# downsample factor

#===============================================================================
# Directories for scripts and advanced settings for processing 
#===============================================================================

#-------------------------------------------------------------------------------
# Fiji settings 
#-------------------------------------------------------------------------------
 
XVFB_RUN="/sw/bin/xvfb-run"				  # virtual frame buffer
Fiji="/sw/users/schmied/packages/Fiji.app.cuda/ImageJ-linux64" # Fiji 

#-------------------------------------------------------------------------------
# Pre-processing 
#-------------------------------------------------------------------------------

#--- Resaving .czi into .tif files----------------------------------------------

jobs_resaving=${job_directory}"/czi_resave/" 			# directory
resaving=${jobs_resaving}"/resaving.bsh" 			# script
 
#--- Resaving ome.tiff into .tif files -----------------------------------------

jobs_resaving_ometiff=${job_directory}"/ometiff_resave/" 	 # directory
resaving_ometiff=${jobs_resaving_ometiff}"/resaving-ometiff.bsh" # script
 
#--- Split channels-------------------------------------------------------------

jobs_split=${job_directory}"/split_channels/" 			# directory
split=${jobs_split}"/split.bsh" 				# script
 
#------------------------------------------------------------------------------- 
# Multi-view Registration 
#-------------------------------------------------------------------------------

jobs_registration=${job_directory}"/registration/" 		# directory
registration=${jobs_registration}"/registration.bsh" 		# script
channel_pattern_beads=${pattern_switch}				# Pattern
type_of_registration="Single-channel" 		# registration parameters
bead_brightness="\"Advanced ...\""
subpixel_localization="\"3-dimensional quadratic fit (all detections)\""
transformation_model="Affine"
imglib_container="\"Array container (images smaller ~2048x2048x450 px)\""
 
#-------------------------------------------------------------------------------
# Timelapse registration
#-------------------------------------------------------------------------------

jobs_timelapse=${job_directory}"/timelapse_registration/" 	# directory
timelapse_registration=${jobs_timelapse}"/time-lapse.bsh" 	# script

#-------------------------------------------------------------------------------
# Multi-view fusion
#-------------------------------------------------------------------------------

jobs_fusion=${job_directory}"/fusion/" 				# directory
fusion=${jobs_fusion}"/fusion.bsh" 				# script
 
fusion_method="\"Fuse into a single image\"" 		    # Fusion parameters
process_views_in_paralell="All" 
blending="blending"
weights="\"content_based_weights_(fast,\""
fused_image_output="\"Save 2d-slices, one directory per time-point\""

#-------------------------------------------------------------------------------
# External transformation
#-------------------------------------------------------------------------------

jobs_external_transformation=${job_directory}"/external_transformation/"
external_transformation=${jobs_external_transformation}"/external_transformation.bsh"
pattern_extrans=${pattern_switch}

#-------------------------------------------------------------------------------
# Multi-view deconvolution 
#-------------------------------------------------------------------------------

jobs_deconvolution=${job_directory}"/deconvolution/"            # directory
deconvolution=${jobs_deconvolution}"/deconvolution.bsh" 	# script
type_of_iteration="\"Efficient Bayesian - Optimization I (fast, precise)\""
osem_acceleration="\"1 (balanced)\""
use_tikhonov_regularization="use_tikhonov_regularization"
Tikhonov_parameter="0.0006"
compute="\"in 512x512x512 blocks\""
compute_on="\"CPU (Java)\""
 
psf_display="\"Do not show PSF's\""
load_input_images_sequentially="load_input_images_sequentially"
fused_image_output="\"Save 2d-slices, one directory per time-point\""

#-------------------------------------------------------------------------------
# Rendering
#-------------------------------------------------------------------------------

Fiji_rendering="/sw/users/schmied/packages/Fiji.app.render/ImageJ-linux64" 

#-------------------------------------------------------------------------------
# hdf5 export
#-------------------------------------------------------------------------------

Fiji_export="/sw/users/schmied/packages/Fiji.app.hdf5/ImageJ-linux64" # Fiji_tobias
path="\"${dir}\"" 					     # data directory
jobs_export=${job_directory}"/hdf5/" 				# directory
export=${jobs_export}"/export.bsh" 				# script
inputFilePattern="\"${pattern_of_spim}\""    # Spim pattern 
angles_export="\"${angles}\""       	     # angles form general
referencetp_export="\"${referencetp}\""      # reference timepoint from general

# overrideImageZStretching does not work
# overrideImageZStretching="true" 

# Not implemented yet
# spimresolutions="{ { 1, 1, 1 }, { 2, 2, 1 }, { 4, 4, 2 }, { 8, 8, 4 } }"
# spimsubdivisions="{ { 32, 32, 4 }, { 16, 16, 8 }, { 8, 8, 8 }, { 8, 8, 8 } }"

# fusionresolutions = "{ { 1, 1, 1 }, { 2, 2, 2 }, { 4, 4, 4 }, { 8, 8, 8 } }"
# fusionsubdivisions = "{ { 16, 16, 16 }, { 16, 16, 16 }, { 8, 8, 8 }, { 8, 8, 8 } }"

