#!/bin/bash
source /projects/pilot_spim/Christopher/pipeline/master

source_rendering=${dir}${source_rendering}
target_rendering=${dir}${target_rendering}

mkdir -p $jobs_rendering
mkdir -p $target_rendering 

for i in $timepoint

do
	job="$jobs_rendering/render-$i.job"
	echo $job
	echo "#!/bin/bash" > "$job"
	echo "$XVFB_RUN -as\"-screen 0 1280x1024x24\" \
		$Fiji_rendering -Xms20g -Xmx20g -Ddir=$source_rendering \
		-Dtimepoint=$i -Dnframes=$nframes -Dtarget_rendering=$target_rendering\
		-Dminimum_rendering=$minimum_rendering -Dmaximum_rendering=$maximum_rendering \
		-Dmin_ch0=$min_ch0 -Dmax_ch0=$max_ch0 -Dmin_ch1=$min_ch1 -Dmax_ch1=$max_ch1 \
		-DzSlices=$zSlices -- --no-splash $rendering" >> "$job"
	chmod a+x "$job"
done


