#!/bin/bash

source /projects/pilot_spim/Christopher/pipeline/master

target_split=${dir}${target_split}

mkdir -p ${jobs_split}
mkdir -p ${target_split}

for i in $timepoint
#for i in 1

do

for a in $angle_prep

do
          	job="$jobs_split/split-$i-$a.job"
                echo $job
                echo "#!/bin/bash" > "$job"
                echo "$XVFB_RUN -a $Fiji -Ddir=$dir -Dtimepoint=$i -Dangle=$a \
		-Dpad=$pad -Dtarget_split=$dir -- --no-splash \
		$split" >> "$job"
                chmod a+x "$job"
        done
done

