#!/bin/bash

source /projects/pilot_spim/Christopher/pipeline/master

mkdir -p $jobs_registration

for i in $timepoint

do
	job="$jobs_registration/register-$i.job"
	echo $job
	echo "#!/bin/bash" > "$job"
	echo "$XVFB_RUN -a $Fiji -Dtype_of_registration=$type_of_registration \
		-Dtype_of_detection=$type_of_detection -Ddir=$dir -Dpattern=$pattern_switch \
		-Dtimepoint=$i -Dangles=$angles -Dbead_brightness=$bead_brightness \
		-Dsubpixel_localization=$subpixel_localization -Dxy_resolution=$xy_resolution \
		-Dz_scaling=$z_scaling -Dtransformation_model=$transformation_model \
		-Dimglib_container=$imglib_container -Dradius1=$radius1 -Dradius2=$radius2 -Dthreshold=$threshold \
		-Dinitial_sigma=$initial_sigma -Dthreshold_gaussian=$threshold_gaussian \
		-- --no-splash $registration" >> "$job"
	chmod a+x "$job"
done

