#!/bin/bash

source /projects/pilot_spim/Christopher/pipeline/master

job="$jobs_export/getnumjobs"
	echo $job
	echo "#!/bin/bash" > "$job"
	echo "$XVFB_RUN -a $Fiji_export -Xmx10g -Dprintnumjobs=true \
		-Dpath=$path -DexportXmlFilename=$exportXmlFilename -Dspimresolutions=$spimresolutions \
        	-Dspimsubdivisions=$spimsubdivisions -DinputFilePattern=$inputFilePattern \
        	-Dchannels=$channels_export -Dangles=$angles_export -Dtimepoints=$timepoint_export \
        	-DreferenceTimePoint=$referencetp_export -DoverrideImageZStretching=$overrideImageZStretching \
        	-DzStretching=$z_scaling -Dfusionresolutions=$fusionresolutions \
        	-Dfusionsubdivisions=$fusionsubdivisions -Dfilepath=$filepath -Dfilepattern=$filepattern \
        	-DnumSlices=$export_numSlices -DsliceValueMin=$sliceValueMin -DsliceValueMax=$sliceValueMax \
        	-DcropOffsetX=$cropOffsetX -DcropOffsetY=$cropOffsetY -DcropOffsetZ=$cropOffsetZ -Dscale=$scale \
		-- --no-splash $export" >> "$job"

chmod a+x "$job"

bsub -q short -n 1 -R span[hosts=1] -o "numjobsout" -e "output/err.%J" "$job"

